### ISSUE TITLE
build.sh does not work as expected in a microsoft/dotnet:2.1-sdk image.

### ISSUE THREAD

**Issue by sprutton1** [nlowe/cake-bootstrap-dotnet#4]
The last exec call in `build.sh` does not work correctly in dotnet:2.1-sdk images. If DRYRUN or SCRIPT_ARGUMENTS are empty, the wrapping quotes are interpreted as additional targets.

```sh
exec dotnet "$CAKE_DLL" "${SCRIPT}" "-verbosity=${VERBOSITY}" "-configuration=${CONFIGURATION}" "-target=${TARGET}" "${DRYRUN}" "${SCRIPT_ARGUMENTS[@]-}"
```
Returns `More than one build script specified.`
```sh
exec dotnet $CAKE_DLL ${SCRIPT} -verbosity=${VERBOSITY} -configuration=${CONFIGURATION} -target=${TARGET} ${DRYRUN} ${SCRIPT_ARGUMENTS[@]-}

```
works.

**Comment by nlowe** [comment]
@sprutton1 I can't reproduce this. Can you give me an example invocation that was causing the issue?
